name: api

on:
  push:
    branches:
      - main
    paths:
      - package.json
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
      - apps/api/**
      - packages/nest/**
      - packages/shared/**
      - packages/tooling/**
      - apps/api/Dockerfile
      - .devops/stack-app.yaml
      - .devops/stack-data.yaml
      - .github/workflows/api.yaml
      - .github/workflows/ci.yaml
      - .github/workflows/cd.yaml
      - .github/workflows/migrate.yaml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  build-push:
    name: Build and push
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/ci.yaml
    with:
      app: api

  migrate:
    name: Migrate
    needs: build-push
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/migrate.yaml
    secrets: inherit

  deploy:
    name: Deploy
    needs:
      - build-push
      - migrate
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/cd.yaml
    with:
      image_root: ${{ needs.build-push.outputs.image_root }}
      image_tag: ${{ needs.build-push.outputs.image_tag }}
      app: api
    secrets: inherit
